const mongoose = require('mongoose');
const crypto = require('crypto');

/**
 * ============================================================
 * PAYMENT TOKEN MODEL - SECURE CARD TOKEN STORAGE
 * ============================================================
 * 
 * Stores encrypted card tokens from Cybersource TMS
 * NOT actual credit card numbers (PCI-DSS compliant)
 * Uses AES-256-CBC encryption with unique IVs
 */

const paymentTokenSchema = new mongoose.Schema(
  {
    // ============================================================
    // CUSTOMER RELATIONSHIP
    // ============================================================

    /**
     * Patient/Customer who owns this token
     * Required - tokens are always tied to a customer
     */
    patientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true
    },

    // ============================================================
    // TOKEN STORAGE (ENCRYPTED)
    // ============================================================

    /**
     * Cybersource token (encrypted)
     * This is NOT the actual card number
     * Generated by Cybersource, stored encrypted locally
     */
    cybersourceToken: {
      type: String,
      required: true,
      unique: true,
      maxlength: 1000 // Encrypted tokens are longer than raw tokens
    },

    /**
     * Encryption IV (Initialization Vector)
     * Different for each token (ensures uniqueness)
     */
    encryptionIv: {
      type: String,
      required: true,
      maxlength: 64
    },

    /**
     * Algorithm used for encryption
     * Stored for future algorithm migration
     */
    encryptionAlgo: {
      type: String,
      default: 'aes-256-cbc',
      maxlength: 50
    },

    // ============================================================
    // CARD INFORMATION (NON-SENSITIVE)
    // ============================================================

    /**
     * Last 4 digits of card (for display only)
     * Safe to display to user
     */
    cardLast4: {
      type: String,
      required: true,
      match: /^\d{4}$/,
      index: true
    },

    /**
     * Card brand (Visa, MasterCard, Amex, Discover)
     */
    cardBrand: {
      type: String,
      enum: ['Visa', 'MasterCard', 'AmericanExpress', 'Discover', 'Diners', 'JCB'],
      required: true,
      index: true
    },

    /**
     * Card expiration month (1-12)
     * Used for display and validation
     */
    expiryMonth: {
      type: Number,
      required: true,
      min: 1,
      max: 12
    },

    /**
     * Card expiration year (4 digits, e.g., 2026)
     * Used for display and validation
     */
    expiryYear: {
      type: Number,
      required: true,
      min: 2024,
      max: 2099
    },

    /**
     * Card holder name hash (hashed for security)
     * Never stored in plain text
     * Used to verify token matches intended cardholder
     */
    cardholderNameHash: {
      type: String,
      sparse: true,
      maxlength: 100
    },

    // ============================================================
    // TOKEN STATUS & LIFECYCLE
    // ============================================================

    /**
     * Current status of token
     * - active: Can be used for payments
     * - expired: Auto-expired after TTL
     * - revoked: Manually revoked by customer
     */
    tokenStatus: {
      type: String,
      enum: ['active', 'expired', 'revoked'],
      default: 'active',
      index: true
    },

    /**
     * When token will auto-expire (24 hours from creation)
     * Expired tokens cannot be used
     */
    expiresAt: {
      type: Date,
      required: true
      // Set TTL index for automatic deletion after expiry
      // MongoDB will delete this document automatically (via schema.index)
    },

    /**
     * When customer manually revoked this token
     */
    revokedAt: {
      type: Date,
      sparse: true,
      index: true
    },

    /**
     * Reason for revocation (deleted card, lost card, etc.)
     */
    revocationReason: {
      type: String,
      maxlength: 200,
      sparse: true
    },

    // ============================================================
    // USAGE TRACKING
    // ============================================================

    /**
     * Number of times this token has been used
     */
    usageCount: {
      type: Number,
      default: 0,
      min: 0
    },

    /**
     * When token was last used
     */
    lastUsedAt: {
      type: Date,
      sparse: true,
      index: true
    },

    /**
     * Is this the customer's default payment method?
     */
    isDefault: {
      type: Boolean,
      default: false,
      index: true
    },

    /**
     * Friendly name for this card (e.g., "My Visa", "Work Card")
     */
    nickname: {
      type: String,
      maxlength: 100,
      sparse: true
    },

    /**
     * Whether token is verified and safe to use
     */
    isVerified: {
      type: Boolean,
      default: false
    },

    /**
     * Date token was verified
     */
    verifiedAt: {
      type: Date,
      sparse: true
    },

    // ============================================================
    // SECURITY & AUDIT
    // ============================================================

    /**
     * Device fingerprint (for fraud detection)
     * Hash of browser/device info
     */
    deviceFingerprint: {
      type: String,
      maxlength: 256,
      sparse: true
    },

    /**
     * IP address where token was created
     */
    createdFromIp: {
      type: String,
      maxlength: 45,
      sparse: true
    },

    /**
     * User agent used when creating token
     */
    createdFromUserAgent: {
      type: String,
      maxlength: 500,
      sparse: true
    },

    /**
     * Country/Location where token was created
     */
    createdFromLocation: {
      type: String,
      maxlength: 100,
      sparse: true
    },

    /**
     * Fraud risk assessment
     * null = not checked, low/medium/high
     */
    fraudRisk: {
      type: String,
      enum: [null, 'low', 'medium', 'high'],
      default: null,
      sparse: true
    },

    /**
     * Admin notes (not visible to customer)
     */
    adminNotes: {
      type: String,
      maxlength: 1000,
      sparse: true
    }
  },
  {
    timestamps: true, // Adds createdAt, updatedAt
    collection: 'paymentTokens'
  }
);

// ============================================================
// INDEXES
// ============================================================

// Fast lookups
paymentTokenSchema.index({ patientId: 1, tokenStatus: 1 });
paymentTokenSchema.index({ patientId: 1, isDefault: 1 });
paymentTokenSchema.index({ patientId: 1, createdAt: -1 });
paymentTokenSchema.index({ cardLast4: 1, cardBrand: 1 });
paymentTokenSchema.index({ lastUsedAt: -1 });

// TTL index - automatically delete expired tokens
paymentTokenSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

// ============================================================
// INSTANCE METHODS
// ============================================================

/**
 * Check if token is active and not expired
 */
paymentTokenSchema.methods.isActive = function() {
  return (
    this.tokenStatus === 'active' &&
    (!this.expiresAt || new Date() < this.expiresAt)
  );
};

/**
 * Check if token is expired
 */
paymentTokenSchema.methods.isExpired = function() {
  return this.expiresAt && new Date() > this.expiresAt;
};

/**
 * Check if token is revoked
 */
paymentTokenSchema.methods.isRevoked = function() {
  return this.tokenStatus === 'revoked';
};

/**
 * Mark token as used
 */
paymentTokenSchema.methods.markAsUsed = function() {
  this.usageCount = (this.usageCount || 0) + 1;
  this.lastUsedAt = new Date();
};

/**
 * Revoke token
 */
paymentTokenSchema.methods.revoke = function(reason = 'User requested') {
  this.tokenStatus = 'revoked';
  this.revokedAt = new Date();
  this.revocationReason = reason;
};

/**
 * Set as default payment method
 */
paymentTokenSchema.methods.setAsDefault = async function() {
  // Unset other tokens as default
  await this.constructor.updateMany(
    { patientId: this.patientId, _id: { $ne: this._id } },
    { isDefault: false }
  );
  
  this.isDefault = true;
};

/**
 * Get display info (safe for frontend)
 */
paymentTokenSchema.methods.getDisplayInfo = function() {
  return {
    id: this._id,
    cardLast4: this.cardLast4,
    cardBrand: this.cardBrand,
    expiryMonth: this.expiryMonth,
    expiryYear: this.expiryYear,
    nickname: this.nickname,
    isDefault: this.isDefault,
    isActive: this.isActive(),
    createdAt: this.createdAt,
    lastUsedAt: this.lastUsedAt
  };
};

/**
 * Get expiry as formatted string
 */
paymentTokenSchema.methods.getExpiryFormatted = function() {
  return `${String(this.expiryMonth).padStart(2, '0')}/${this.expiryYear}`;
};

/**
 * Check if token expires soon (within 30 days)
 */
paymentTokenSchema.methods.expiresSoon = function() {
  const thirtyDaysFromNow = new Date();
  thirtyDaysFromNow.setDate(thirtyDaysFromNow.getDate() + 30);
  
  const expiryDate = new Date(this.expiryYear, this.expiryMonth - 1, 1);
  
  return expiryDate < thirtyDaysFromNow && expiryDate > new Date();
};

// ============================================================
// STATIC METHODS
// ============================================================

/**
 * Find active tokens for a patient
 */
paymentTokenSchema.statics.findActiveByPatient = function(patientId) {
  return this.find({
    patientId,
    tokenStatus: 'active',
    expiresAt: { $gt: new Date() }
  });
};

/**
 * Find default token for a patient
 */
paymentTokenSchema.statics.findDefaultByPatient = function(patientId) {
  return this.findOne({
    patientId,
    isDefault: true,
    tokenStatus: 'active',
    expiresAt: { $gt: new Date() }
  });
};

/**
 * Find by token ID and patient (security check)
 */
paymentTokenSchema.statics.findByIdAndPatient = function(tokenId, patientId) {
  return this.findOne({
    _id: tokenId,
    patientId
  });
};

/**
 * Find or create default token for patient
 */
paymentTokenSchema.statics.getActiveTokens = function(patientId) {
  return this.find({
    patientId,
    tokenStatus: 'active',
    expiresAt: { $gt: new Date() }
  }).sort({ isDefault: -1, createdAt: -1 });
};

/**
 * Count active tokens for patient
 */
paymentTokenSchema.statics.countActiveByPatient = function(patientId) {
  return this.countDocuments({
    patientId,
    tokenStatus: 'active',
    expiresAt: { $gt: new Date() }
  });
};

/**
 * Clean up expired tokens (manual trigger)
 * MongoDB TTL index does this automatically, but this is for manual cleanup
 */
paymentTokenSchema.statics.cleanupExpired = async function() {
  const result = await this.deleteMany({
    expiresAt: { $lt: new Date() }
  });
  
  return result;
};

// ============================================================
// SCHEMA HOOKS
// ============================================================

/**
 * Validate token data before saving
 */
paymentTokenSchema.pre('save', function(next) {
  // Ensure only one default token per patient
  if (this.isDefault && this.isModified('isDefault')) {
    // This will be handled by setAsDefault() method
  }

  // Ensure expiryMonth is valid
  if (this.expiryMonth < 1 || this.expiryMonth > 12) {
    return next(new Error('Invalid expiry month'));
  }

  next();
});

/**
 * Prevent modification of critical fields
 */
paymentTokenSchema.pre('save', function(next) {
  if (this.isModified('cybersourceToken')) {
    return next(new Error('Cannot modify stored token'));
  }

  next();
});

/**
 * Log token operations to audit
 */
paymentTokenSchema.post('save', function(doc) {
  // Could integrate with PaymentAudit model here
  // For now, just log the operation
  if (this.isModified('tokenStatus')) {
    console.log(`Token ${doc._id} status changed to ${doc.tokenStatus}`);
  }
});

// ============================================================
// CREATE MODEL
// ============================================================

module.exports = mongoose.model('PaymentToken', paymentTokenSchema);
